### ISSUE TITLE
Dataclasses issue when importing from immudb

### ISSUE THREAD

**Issue by adrnsrn7** [codenotary/immudb-py#68]
When deploying to lambda using serverless, there is an error with dataclasses. Upon searching, the most common solution is to remove the installation of dataclasses since it's not a necessity for python above 3.6 but deploying with serverless only gives an option to add required packages and no option to remove any. When installing immudb-py, it forces an installation of dataclasses 0.6 which is not necessary and only gives errors. Tried using python 3.8 and 3.10 with both the same results.

[ERROR] AttributeError: module 'typing' has no attribute '_ClassVar'
Traceback (most recent call last):
  File "/var/lang/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/task/app.py", line 13, in <module>
    from immudb import ImmudbClient
  File "/var/task/immudb/__init__.py", line 13, in <module>
    from immudb.client import ImmudbClient
  File "/var/task/immudb/client.py", line 19, in <module>
    from immudb import datatypes
  File "/var/task/immudb/datatypes.py", line 26, in <module>
    class SetResponse:
  File "/var/task/dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "/var/task/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/var/task/dataclasses.py", line 800, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "/var/task/dataclasses.py", line 800, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "/var/task/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/var/task/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar

**Comment by SimoneLazzaris** [comment]
Hi @adrnsrn7 thanks for the report.
When we created immudb-py we wanted to support older python version, so we included `dataclasses` in the setup requirements. As you pointed out, that is not necessary with modern (3.7) python versions.

I've created a branch where that removes that packages: test/no_dataclasses.
Can you try that branch? You should be able to install it with `python setup.py install`

**Comment by adrnsrn7** [comment]
I was able to get it working by placing the new branch on my requirements.txt
![image](https://github.com/codenotary/immudb-py/assets/89364005/1cdf69b9-57a1-4469-935e-e7dd823ed03e)
So far there are no errors with both serverless framework and chalice.

Thanks for your help.
